import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center py-12 px-24">
          <nav className="mb-12 flex flex-col items-center">
            <Link href="/">
              <h1 className="font-bold text-xl italic border-b-2 mb-4 hover:text-green-200 hover:border-green-200">
                My blog
              </h1>
            </Link>
            <Link href="/about" className="italic text-sm hover:text-green-200">
              About
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
